# Generated by Django 5.2.5 on 2025-08-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameClass', models.CharField(choices=[('MMC', 'Модель техники'), ('MMT', 'Модель двигателя'), ('MT', 'Модель трансмиссии'), ('MDA', 'Модель ведущего моста'), ('MCA', 'Модель управляемого моста'), ('TTO', 'Вид ТО'), ('FND', 'Узел отказа'), ('WTR', 'Способ восстановления')], default='MMC', max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavNumberMachine', models.CharField(max_length=20, unique=True)),
                ('zavNumberMotor', models.CharField(max_length=20)),
                ('zavNumberTransmission', models.CharField(max_length=20)),
                ('zavNumberDA', models.CharField(max_length=20)),
                ('zavNumberCA', models.CharField(max_length=20)),
                ('deliveryContract', models.CharField(max_length=50)),
                ('shipDate', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=100)),
                ('deliveryAddress', models.CharField(max_length=150)),
                ('package', models.TextField(blank=True)),
                ('client', models.CharField(max_length=150)),
                ('modelControllAxile', models.ForeignKey(limit_choices_to={'nameClass': 'MCA'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelControllAxile', to='serviceBook.manual')),
                ('modelDriveAxile', models.ForeignKey(limit_choices_to={'nameClass': 'MDA'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelDriveAxile', to='serviceBook.manual')),
                ('modelMachine', models.ForeignKey(limit_choices_to={'nameClass': 'MMC'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelMachine', to='serviceBook.manual')),
                ('modelMotor', models.ForeignKey(limit_choices_to={'nameClass': 'MMT'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelMotor', to='serviceBook.manual')),
                ('modelTransmission', models.ForeignKey(limit_choices_to={'nameClass': 'MT'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelTransmission', to='serviceBook.manual')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceCompany', to='serviceBook.service')),
            ],
        ),
    ]
