# Generated by Django 5.2.5 on 2025-08-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
