# Generated by Django 5.2.5 on 2025-08-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0002_alter_manual_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='serviceBook.machine')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('typeTO', models.ForeignKey(limit_choices_to={'nameClass': 'TTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='typeTO', to='serviceBook.manual')),
            ],
        ),
    ]
