# Generated by Django 5.2.5 on 2025-08-10 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0003_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to',
            name='date',
        ),
        migrations.AddField(
            model_name='to',
            name='dateOrder',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='to',
            name='dateTO',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='to',
            name='numberOrder',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='to',
            name='runTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='to',
            name='serviceTO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serviceTO', to='serviceBook.service'),
        ),
    ]
