# Generated by Django 5.2.5 on 2025-08-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0008_reclamation_machine_alter_reclamation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to',
            old_name='id',
            new_name='machine',
        ),
    ]
