# Generated by Django 5.2.5 on 2025-08-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0009_rename_id_to_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='shipDate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
