# Generated by Django 5.2.5 on 2025-08-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0010_alter_machine_shipdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='to',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='to',
            name='machine',
        ),
        migrations.CreateModel(
            name='TOMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='serviceBook.to')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='serviceBook.machine')),
            ],
        ),
        migrations.AddField(
            model_name='to',
            name='machine',
            field=models.ManyToManyField(through='serviceBook.TOMachine', to='serviceBook.machine'),
        ),
    ]
