# Generated by Django 5.2.5 on 2025-08-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0011_to_id_remove_to_machine_tomachine_to_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='machine',
        ),
        migrations.CreateModel(
            name='ReclamationMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_machine', to='serviceBook.machine')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamation', to='serviceBook.reclamation')),
            ],
        ),
        migrations.AddField(
            model_name='reclamation',
            name='machine',
            field=models.ManyToManyField(through='serviceBook.ReclamationMachine', to='serviceBook.machine'),
        ),
    ]
