# Generated by Django 5.2.5 on 2025-08-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0012_remove_reclamation_machine_reclamationmachine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='tomachine',
            name='TO',
        ),
        migrations.RemoveField(
            model_name='tomachine',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='to',
            name='machine',
        ),
        migrations.DeleteModel(
            name='ReclamationMachine',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReclamationMachine', to='serviceBook.machine'),
        ),
        migrations.DeleteModel(
            name='TOMachine',
        ),
        migrations.AddField(
            model_name='to',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TOMachine', to='serviceBook.machine'),
        ),
    ]
