# Generated by Django 5.2.5 on 2025-08-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0013_remove_reclamation_machine_remove_tomachine_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceBook.machine'),
        ),
        migrations.AlterField(
            model_name='to',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceBook.machine'),
        ),
    ]
